version: 2

sources:
  - name: source_bronze
    database: pysparkdbt
    schema: bronze 
    tables:
      - name: trips
      - name: customers

  - name: source_silver
    database: pysparkdbt
    schema: silver    
    tables:
      - name: customers
      - name: locations
      - name: payments
      - name: drivers
      - name: vehicles